<?php

namespace App\Widgets;

/**
 * Created by PhpStorm.
 * User: Sunlong
 * Date: 2017/11/9
 * Time: 1:10
 */
class ImageLink extends Link
{
    public function getData(array $params = [])
    {
        return parent::getData($params); // TODO: Change the autogenerated stub
    }
}